# role: ethpandaops.general.bootstrap
bootstrap_default_user_authorized_keys_github_team_cl:
  - AgeManning
  - ethdreamer
  - paulhauner
  - pawanjay176
  - michaelsproul
  - potuz
  - nisdas
  - antondlr
  - realbigsean

# role: validator_keys
validator_keys_sync_files:
  - src: "{{ inventory_dir }}/files/validator_keys/{{ inventory_hostname }}/keys/"
    dest: "{{ lighthouse_validator_datadir }}/keys/"
  - src: "{{ inventory_dir }}/files/validator_keys/{{ inventory_hostname }}/secrets/"
    dest: "{{ lighthouse_validator_datadir }}/secrets/"

# role: ethpandaops.general.ethereum_node
ethereum_node_cl: lighthouse

# role: ethpandaops.general.lighthouse
lighthouse_container_image: "{{ default_ethereum_client_images.lighthouse }}"
lighthouse_container_env:
  VIRTUAL_HOST: "{{ ethereum_node_beacon_hostname }}"
  VIRTUAL_PORT: "{{ ethereum_node_cl_ports_http_beacon | string }}"
  LETSENCRYPT_HOST: "{{ ethereum_node_beacon_hostname }}"
lighthouse_container_volumes:
  - "{{ lighthouse_datadir }}:/data"
  - "{{ lighthouse_auth_jwt_path }}:/execution-auth.jwt:ro"
  - "{{ eth_testnet_config_dir }}:/network-config:ro"
lighthouse_container_command_extra_args:
  - --testnet-dir=/network-config
  - --debug-level=debug
  - --prune-payloads=false
  - --dummy-eth1
lighthouse_validator_container_volumes:
  - "{{ lighthouse_validator_datadir }}:/validator-data"
  - "{{ eth_testnet_config_dir }}:/network-config:ro"
lighthouse_validator_container_command_extra_args:
  - --testnet-dir=/network-config
  - --graffiti={{ ethereum_node_cl }}/{{ ethereum_node_el }}
lighthouse_validator_datadir: /data/lighthouse-validator


# role: ethpandaops.general.bootstrap
bootstrap_default_user_authorized_keys_github_team_el:
  - garyschulte
  - jflo
  - fab-10
  - matkt
  - gezero
  - siladu
  - pinges
  - jframe

# role: ethpandaops.general.ethereum_node
ethereum_node_el: besu

# role: ethpandaops.general.besu
besu_container_image: "{{ default_ethereum_client_images.besu }}"
besu_container_env:
  VIRTUAL_HOST: "{{ ethereum_node_rcp_hostname }}"
  VIRTUAL_PORT: "{{ ethereum_node_el_ports_http_rpc | string }}"
  LETSENCRYPT_HOST: "{{ ethereum_node_rcp_hostname }}"
besu_container_volumes:
  - "{{ besu_datadir }}:/data"
  - "{{ besu_auth_jwt_path }}:/execution-auth.jwt:ro"
  - "{{ eth_testnet_config_dir }}:/network-config:ro"
besu_container_command_extra_args:
  - --genesis-file=/network-config/besu.json
  - --rpc-http-api=ADMIN,DEBUG,ETH,MINER,NET,TRACE,TXPOOL,WEB3
  - --sync-mode=FULL
  - --data-storage-format=BONSAI
  - --tx-pool-limit-by-account-percentage=1
  - --kzg-trusted-setup=/network-config/trusted_setup.txt
  - --rpc-http-max-active-connections=250

# role: ethpandaops.general.prometheus
prometheus_config: |
  global:
    scrape_interval: 30s
    evaluation_interval: 30s
    scrape_timeout: 10s
    external_labels:
      instance: "{{ inventory_hostname }}"
      ip_address: "{{ ansible_host }}"
      network: "{{ ethereum_network_name }}"
      testnet: "{{ ethereum_network_name }}"
      execution_client: "{{ ethereum_node_el }}"
      consensus_client: "{{ ethereum_node_cl }}"
  remote_write:
    - queue_config:
        batch_send_deadline: 5s
        max_backoff: 500ms
        max_samples_per_send: 500
        min_backoff: 50ms
        max_shards: 100
      url: {{ prometheus_remote_push_url }}
      remote_timeout: 10s
      basic_auth:
        username: {{ prometheus_remote_write_username }}
        password: {{ prometheus_remote_write_password }}
  scrape_configs:
    - job_name: "prometheus"
      metrics_path: "/metrics"
      static_configs:
        - targets: ["localhost:9090"]
          labels:
            instance: "{{ inventory_hostname }}"
    - job_name: "node"
      metrics_path: "/metrics"
      static_configs:
        - targets: ["172.17.0.1:9100"]
          labels:
            instance: "{{ inventory_hostname }}"
    - job_name: "exporter"
      metrics_path: "/metrics"
      static_configs:
        - targets: ["ethereum-metrics-exporter:9090"]
          labels:
            instance: "{{ inventory_hostname }}"
    - job_name: "consensus_node"
      metrics_path: "/metrics"
      static_configs:
        - targets: ["beacon:{{ ethereum_node_cl_ports_metrics }}"]
          labels:
            instance: "{{ inventory_hostname }}"
    - job_name: "besu"
      static_configs:
        - targets: ["execution:{{ ethereum_node_el_ports_metrics }}"]
          labels:
            instance: "{{ inventory_hostname }}"
