tx_fuzz_user: "tx_fuzz"
tx_fuzz_cleanup: false # when set to "true" it will remove the container

tx_fuzz_container_name: "tx_fuzz"
tx_fuzz_container_image: "ethpandaops/tx-fuzz:latest"
tx_fuzz_container_env: {}
tx_fuzz_container_ports: []
tx_fuzz_container_volumes: []

tx_fuzz_container_stop_timeout: "300"
tx_fuzz_container_networks: "{{ docker_networks_shared }}"

tx_fuzz_container_command:
  - spam
  - --no-al
  - --rpc={{ tx_fuzz_rpc_url }}
  - --sk={{ tx_fuzz_private_key }}

tx_fuzz_rpc_url: http://besu:8545
tx_fuzz_private_key: "{{ tx_fuzz_privatekey }}"
tx_fuzz_public_key: "0xfbC5464ccE6B3106ab7Daf278f8d94de1F306741"