secret_ethstats: ENC[AES256_GCM,data:o0ehCWXYsffvgGYL9fRR,iv:4EYtvgjXnZ6wqKjxNAOcc2LcOyunXu8hV2NLzBm+uN4=,tag:SY01DZXjwdw1NSJgdjWuWg==,type:str]
secret_prometheus_remote_write:
    username: ENC[AES256_GCM,data:VpjUJ6I4MrCskLq37XAd,iv:KmGa+FBiTWpA+VbBMw02j394YAymbc8oIpsPeWHNnBo=,tag:CrQIkPno+6GbGmYF3EJUOA==,type:str]
    password: ENC[AES256_GCM,data:qn2ICer+CMHyZhhyyEjwK56klDur2I1Bb4rRiFrcRIsZSUgd,iv:O8LVGGAo9XqTJ1sKm4vjFwJ3Evye42JKL6iyeCW3ypk=,tag:dBe8OMj2ke80A6fdatKOQg==,type:str]
secret_nginx_shared_basic_auth:
    name: ENC[AES256_GCM,data:+Kn3,iv:JiGNhNOwMPigHT7s5VTjLPkRE6XuZNo3XlWGNNhj4ew=,tag:s3buqedEkeyZtQ9a3ZL+9g==,type:str]
    password: ENC[AES256_GCM,data:6zU/+5q8+XGtxCvO0deL,iv:EhjgTO6RIjrpxkNvqenfEd+AQ8TyEq6eTvtG19UEQq8=,tag:3XeeOmG8MryI08N9ysUcHg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-04-18T09:37:49Z"
    mac: ENC[AES256_GCM,data:/ebjn5DE1xuVLYJPlF9DDargW8loSFjztrfRqIZIimeR6/02wFrdI4427d/DpHiBjZ1ys+ubrr1aUvLV2as0SfCn03Xu7fbvoB4ut5BBYpPp19bcjAAfK1VRzlx/vyPxu8bfQ5pPTQznELplIyVUTGHyLWK0hPQtASMwItzeivs=,iv:DacP/2rMPab+/MXf5U+LPllMriAExnKCMciCLw1AIYU=,tag:kKw9gAXpQNznPstfwCanbA==,type:str]
    pgp:
        - created_at: "2023-04-12T19:24:34Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA32GcoRiZf6pAQ/8DLt5VIbfHSz+c8OyBhznEvd84FWvqeYE6Co5nlUmMniW
            w5jU9vJ2UeoQUw8wWndKa0QdO5Ymaj8Mnhi0qZcEh05tFJz4Ph6s2vB7wx4H6ywc
            gjXlFFS5sk1toYQ7cmA8srGxKUaoxnshoQfU3F3v7VfVoj6khRyUi7RkXRliRoA+
            mxu4YLOmZWU+ztDUkPtLzDb7On64X7f2Y9H4KEHsJ+KZtl9XR/pHJfpvWDayK2MJ
            k22bSRaua0Sc3AGG54oEuJpjXNk9ptxiVAk7uOU2oOLfU1xNkRGAdIN6MKC+0lQ2
            3nxXQq1nNUF8MOkMO2zD1Sqcry1xFTA7ElUbW4AwgLOo+PgVe1PCGHf4ClBPJZ9R
            ac+KMUSq7+gcEQoECljJPt6SQ/bzZtY6ERL9RnnH9YGBDk+XeVycvm3V0tilmkPm
            Tw6AsDOIluEF57SNS9yN2SuVbGHpmEOtNc5tOBj6R+Fe0a3qgmNzD8x5QSvfZ5jD
            5sK0BrKNNnNZsGo4Uy59tz7fEGq0As91Tf4Kffl+DpD5M5PG+yehJAGII1BND/fm
            x+N0I07Hypo8yDP+Aa6gIRjfRZ4ck6ZHp47wBWffxOvYUHAnWhWUdXOhhwwSguy4
            IC6GpmKix/5FMXWQZEguxDqlWo8lEYv+LT9XjRepaY8qY9yNP6gIN4X0gcAxUzTS
            UQGfaWcbmnVr+rfRfHpB9CqTpguQI/fMzpmpfm3NR8G9L9hML6bT2j5GdH3a5nCO
            UEUo8Iz/ZwRIE8f3MWVs8i99pQ+ybeKCZllF2bOm76GCwA==
            =zXiY
            -----END PGP MESSAGE-----
          fp: 80DB2B4EF6CA4D9829C280605636BC0E08138A24
        - created_at: "2023-04-12T19:24:34Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA87Wber4r4dGARAAhTrpEJI1mskpq/m4XJw/KYJrcIIzBiR2vweTbFZElZaf
            wjJctcSc7ObAoDpqxgwRiovVvAYAq6CGL5ZRSenfqXqKJ7CrQTFPjrseKMzEJY22
            gVRZ8VY1kaBBFTJt+skr9r4OPLafqOYDwj4dTx/ivedpKtULVm+5/VmX5qSMhsQq
            hxRkVKUc+Kc0mVB6sbx4d9EQFthmKwxYT30YR7R4KZ/HjauuReDjmqyhrXiVTFSm
            3MujF8TVHWtCgJKSDDLpxa6vY0aI0mkUUmGgbgbu0mdi/0AUaUE3No7WxXltHMkD
            +W+5aG/22El7QVMYjp65VAw78Tn/jKdUOX31wIQsNx17yl/Q36OyA9tGSO+PjdWz
            Wr9tbu7zydX5PNT3WW+NExFhSh/vQ3nSP5DR4jWEBZ2CBp0Gf4it7NLNG3ptrN19
            hAAf+kWkFUSUAxQxGwqTAI6pcSnFbR7oQv4keJvvv6I1Mx8B/zyhlFz9T+eRyqG3
            CzyxE4NDm28OQGk4PssYXPyR0U8/SLZBXIgPYXGAY2ETmHEHK7VBmz7rNFS7ZrBD
            hTyYuXN3+sV/gxugMKKLII7cWPqycFIkI7BeZzihHM2luWmTT1AydX23yVVjrhOP
            mpSMwb+2TeeAfuHUvyup9R2EsC4SY9w7e3oDcAcmPxmt0hhsz/6ToVocX8pyN5XS
            UQH1b+N65VlsVn1wV6UHR+8r7moIv9EMWuoIwnyMqwIH+rCp/mzGlSZ7nzv9ubJI
            w+OKWgJi09Dqs8eEzfXYRaaVNgu0khFqCE/7bL/XmszwuQ==
            =c5Pi
            -----END PGP MESSAGE-----
          fp: 69F66EEA7AE36CCB77DDB8CA1BC39532FB4A2DBD
        - created_at: "2023-04-12T19:24:34Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA4hw3nPn82LyAQ//QM5DbXnxFt25w0bhQ4suq6Wd1/jPTEUNjB3+iC4eu7Dc
            UVvU+goyzvRUsIu59DF1ibYaTa7KMgPwSHXXWxDu5l1wiw7Ksz/eBlSSFIUTrPIu
            29Oh70CeUnhat651ANOHlzVZDG2aLosrS8OitC8vevxcNJ7x6SFaKaQbmU4BzeiW
            Shxn7zgdmUaSomfgj6sY4Ng4Qmn5de8adpq9DZZqqFvfMALmQHX0jM2FnNWx6nEV
            nMCgMRzYkKMvrfZAoJw2Gdd//Sqw/46HXZbLAufDiezXJivGzooLHiLyWkG5Bxtg
            QMwHJX03bZZ9eHvizoGkl9Thk3UUUbVtRGApXuLpbrQ30RZXhRx/SxuMiWx2dnvW
            BCol25yVAAOxZMrYyWJcKPSK/+XUSMv/buKeFX70v6JzNpuRKC6L5sQEnxd5ODO6
            WeEMciFUu7+nOz8sIuDs7JXYxYnfV+qs9ur5QcPrMvbG90egoJSjvSa+12ZcCsT4
            tXtxCUQK9o6XGlsxY0TAmNmxp4gHGhJ43GP76pP/zWAXXc2t/cJzBLJimlB/8El3
            CYKbjWJFRIcHxoj82qrndpXN/KZ5c3XEQewZvcy9zzplOQG1CHbLtOTSNuKObn9m
            /8NCmqj/Ns40h9U0Aa5ijmiCK09yOHWstt61Jw+9UldFQ/zbkUn6CMfu3ASWtHTS
            UQErLYrs58REPGljK/rp9/jRlA3qdke3vTJQm7dv45XZpRfSk/1YhV6uy5wvz/ns
            rAZ5uhp0NhQSp2uyxJyAR6rn/4ePB/J+uPcy6XKMwyCV0w==
            =qXw4
            -----END PGP MESSAGE-----
          fp: D1002590180DE371BCB455EAEFCD4ACD0B4D3F6E
        - created_at: "2023-04-12T19:24:34Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMAw01qfIBwY0JARAAuAjVQeiBYid/VM21zbzGOBQBbx/uWp+XxtnrOExXApmh
            HkG9fAxu3HQE5fesl+PnztQeXR6u5Rsyd6Hq+FTSzzduj1Sl2lDTTXeQszCM6ewO
            JkHryXoo2aoVIgv9emTmZyDTaukXKmo8vC02Ji1AjMhUEKXJwVxidrrm+6VhS6M6
            c7rTAmoqzRv4VUukf8Bqju2ueLPnfZmM1jW+GBZ8PGJjxnfDRm4E4qP3+rxC+zs4
            k1jXaoBrA2gYX6zIvFzmmhHDISb6ypaiORpWlX20P2Zu2b7G0yTHAIzMthOuXywB
            GjzcoKHigEBtPSQsfE6Qb9oAGCCNeu6ZbG5Z00cI3tB5QaxP7PN2C60wDSeiITEZ
            9RPiWOuJMwUH1xlSHNe3tYF2672MFdFHHN8VV6Upz1F8KR4mvMUeO+DsfiTpt9jo
            lKsEgRMSzHfvPSPfUTr2Bwx0/ThrBFysx+E3Pp4dKVT+E6qnf6c1Zz/nDAFWH6yb
            hGL8qSMYwWPX4/8oztANT6IOlPxheyVI/0d3RkUxy6tBz2oRZR1Rxq03hfxjBLyH
            fP2Wi+poo11hhNEGuFwQjvbdxUI+URTAL7mM/TYA5rQQLR8AoR2qKhpaJsJSi8ks
            u7L7PMQaa4ZUPffXA23ROy0PTUVB7bQd7Q8aYt+hY/kpQjGthQzHDCgczG7FehfS
            UQH/f4lpIs39YaQrf3vGezOG646RsnK2gqARHKGV+kdHdBCscviX7CCA2ezLJQDv
            ZbdPOKMESg9omJ/XO2NVLBvy6YyqXu7bXryj4K04f8JLxg==
            =NRov
            -----END PGP MESSAGE-----
          fp: B9F81F327CF5346860E85269D7AF98F214C59E4E
        - created_at: "2023-04-12T19:24:34Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcBMAwDFOgk9tOQ+AQgAojthgJchAiasbZ5AUuFLe9e6RdTHduhD0j+LZTW2eFAg
            jet80KcOYyrMAXcBjty7k50ZXwvGU5WkhmHtxE9dGK9dvvupJdnbT0H7tFprbgNj
            X2ZlkxffAfbkWMMPOeIQQU3eGhRDqj+DWet4ulIQTVyVuwpMrFVqOvHGLEzvJI5k
            KrmziwRaW3rNnDyKrYWfOVH2lhWINMy+B/bztmkaESfuvs2vQgk55GGhWXcb19li
            tc9KDtLSRgCvG62Lnrr0nPXB4SvV1X3l8kaxdsq3cqX+3XfJjRoxC8nlqo6KzTCQ
            ci6UKVd8vehN+bbD9n2WpZq4vxX58qUBHkBalG96udJRAdlssfeXKcfgFmtfgKz/
            PNRJyO6zYNojsGJaVV5P/Qn+zgcqLgbM+LmdDwQ0vb2C7M7zYAh0sK2QG7rlmVbj
            uhnRTaJhGbm3yS+nXcbsasPd
            =GrR3
            -----END PGP MESSAGE-----
          fp: 0600D41E1313E31016F7C55BF597BC0C5F22D1A2
    unencrypted_suffix: _unencrypted
    version: 3.7.3
