default_ethereum_client_images:
  besu: kevinbogner/6110-besu:0403
  lighthouse: kevinbogner/6110-lh:0410

default_tooling_images:
  ethereum_metrics_exporter: ethpandaops/ethereum-metrics-exporter:0.21.0